# borrowed from astropy

name: petsc

dependencies:
  - python>=3
  - numpy
  - cython
  - matplotlib
  - scipy
  - pillow
  - pyyaml
  - jinja2
  - h5py
  - scikit-image
  - pandas
  - pytz
  - beautifulsoup4
  - ipython
  - mpmath
  - pytest
  - pip:
    - sphinx-gallery>=0.1.12
    - jplephem

